name: Build
on: [push]
jobs:
  print-greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        env:
          MY_VAR: This code is uploaded by
          FIRST_NAME: Shihan
          SECOND_NAME: Zhuofan
        run: |
            echo $MY_VAR $FIRST_NAME and $SECOND_NAME .
  check-packets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: check flask is required
        run: |
          if grep -q flask requirements.txt; then
            echo "Package found in requirements.txt"
          else
            echo "Package not found in requirements.txt"
            exit 1
          fi
      - name: check flake8
        run: pip freeze | grep flake8
      
  python-formatting:
    runs-on: ubuntu-latest
    needs: check-packets
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        run: flake8 --ignore=E501 api/
  run-unit-tests:
    needs: python-formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install flask
        run: pip install flask
      - name: Install pytest
        run: pip install pytest
      - name: Run Unit Tests
        run: pytest api/*.py

  deploy-to-vercel:
    needs: run-unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'